name: Vanish
main: Vanish\Vanish
api:
- 3.0.0
- 4.0.0
version: 1.0
author: PMExperts
#TeamTuranic #PMExperts

commands:
  vanish:
    description: "Vanish command"
    usage: "/vanish <on/off>"
    permission: vanish.command
  v:
    description: "Vanish command"
    usage: "/vanish <on/off>"
    permission: vanish.command

permission:
  vanish.command:
    default: op
    description: "Permission for vanish command"
